name: Lint and test

on:
  push:
    branches-ignore: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  setup:
    name: Setup and install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Lint scripts
        run: npm run lint:scripts
      - name: Lint styles
        run: npm run lint:styles
      - name: Test application
        run: npm run test
